// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _poly_HH_
#define _poly_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct poly : public sc_module {
    // Port declarations 7
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > x;
    sc_out< sc_lv<16> > y;
    sc_out< sc_logic > y_ap_vld;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    poly(sc_module_name name);
    SC_HAS_PROCESS(poly);

    ~poly();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<16> > tmp_3_fu_32_p0;
    sc_signal< sc_lv<16> > tmp_3_fu_32_p2;
    sc_signal< sc_lv<16> > tmp_1_fu_38_p1;
    sc_signal< sc_lv<16> > tmp_1_fu_38_p2;
    sc_signal< sc_lv<16> > tmp1_fu_50_p0;
    sc_signal< sc_lv<16> > tmp1_fu_50_p1;
    sc_signal< sc_lv<16> > tmp1_fu_50_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_true;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_const_lv16_2;
    static const sc_lv<16> ap_const_lv16_1;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_tmp1_fu_50_p0();
    void thread_tmp1_fu_50_p1();
    void thread_tmp1_fu_50_p2();
    void thread_tmp_1_fu_38_p1();
    void thread_tmp_1_fu_38_p2();
    void thread_tmp_3_fu_32_p0();
    void thread_tmp_3_fu_32_p2();
    void thread_y();
    void thread_y_ap_vld();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
